name: Test and Deploy
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9.14
      - uses: actions/setup-python@v4
      - with:
        python-version: 3.9.14
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Collect Static Files
        run: python manage.py collectstatic
      - name: Run Test
        run: python manage.py test

  DeployHeroku:
    needs: Test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install dpl
        run: gem install dpl
      - name: Install Heroku CLI
        run: wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Deploy to Heroku
        run: dpl --provider=heroku --app=$HEROKU_APP_NAME --api_key=$HEROKU_API_KEY
      - name: Migrate Database
        run: heroku run --app=$HEROKU_APP_NAME migrate